config/routes.rb
Rails.application.routes.draw do
  resources :companies do
    resources :jobs
  end

  resources :categories, except: [:delete]
  resources :comments, only: [:create]
  resources :contacts, only: [:create]
  resources :dashboard, only: [:index]
  resources :jobs, only: [:index]
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :title, presence: true
  validates :title, uniqueness: true
  has_many :jobs
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :job
end

app/models/company.rb
class Company < ActiveRecord::Base
  validates :name, :city, presence: true
  validates :name, uniqueness: true
  has_many :jobs, dependent: :destroy
  has_many :contacts, dependent: :destroy

  def self.ordered
    order(:city)
  end

  def self.top_three
    company_avg = Company.all.group_by do |company|
      company.jobs.average(:level_of_interest).round
    end
    length_check(company_avg.sort.reverse)
  end

  def self.length_check(sorted_averages)
    if sorted_averages.count >= 3
      sorted_averages[0..2]
    elsif sorted_averages.count == 2
      sorted_averages[0..1]
    else
      sorted_averages
    end
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :position, presence: true
  validates :email, presence: true

  belongs_to :company
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, :level_of_interest, presence: true
  belongs_to :company
  belongs_to :category
  has_many :comments

  def self.ordered_level_of_interest
    group(:level_of_interest).order(level_of_interest: :desc).count
  end

  def self.interest
    order(:level_of_interest).reverse
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "#{@category.title} created!"
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    if @category.save
      flash[:success] = "#{@category.title} updated!"
      redirect_to category_path(@category)
    else
      render :edit
    end
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    job = Job.find(params[:job_id])
    @comment = job.comments.new(comment_params)
    @comment.save
    redirect_to company_job_path(@comment.job.company, @comment.job)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
    @ordered = @companies.ordered
    if params[:sort]
      render :job_city_sort
    elsif params[:location]
      @company = Company.where(city: params[:location])
      render :city
    end
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      flash[:success] = "#{@company.name} added!"
      redirect_to company_path(@company)
    else
      render :new
    end
  end

  def show
    company = Company.find(params[:id])
    redirect_to company_jobs_path(company)
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    @company.update(company_params)
    if @company.save
      flash[:success] = "#{@company.name} updated!"
      redirect_to company_path(@company)
    else
      render :edit
    end
  end

  def destroy
    company = Company.find(params[:id])
    company.destroy

    flash[:success] = "#{company.name} was successfully deleted!"
    redirect_to companies_path
  end


  private

  def company_params
    params.require(:company).permit(:name, :city)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def create
    company = Company.find(params[:company_id])
    @contact = company.contacts.new(contact_params)
    @contact.save
    redirect_to company_jobs_path(@contact.company)
  end

  private

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :position, :email)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @jobs = Job.all
    @top_three = Company.top_three
    @cities = Company.all.pluck(:city).uniq
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    if params[:sort]
      @jobs = Job.all
      render :interest
    else
      @contact = Contact.new
      @company = Company.find(params[:company_id])
    end
  end

  def new
    @categories = Category.all
    @company = Company.find(params[:company_id])
    @job = Job.new()
  end

  def create
    @categories = Category.all
    @company = Company.find(params[:company_id])
    @job = @company.jobs.new(job_params)
    if @job.save
      flash[:success] = "You created #{@job.title} at #{@company.name}"
      redirect_to company_job_path(@company, @job)
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @job = Job.find(params[:id])
    @comments = Comment.all.reverse
  end

  def edit
    @categories = Category.all
    @company = Company.find(params[:company_id])
    @job = Job.find(params[:id])
  end

  def update
    @company = Company.find(params[:company_id])
    @job = Job.find(params[:id])
    if @job.update(job_params)
      flash[:success] = "#{@job.title} updated!"
      redirect_to company_job_path(@company, @job)
    else
      render :edit
    end
  end

  def destroy
    @company = Company.find(params[:company_id])
    @job = Job.find(params[:id])
    @job.delete

    flash[:success] = "#{@job.title} was successfully deleted!"
    redirect_to company_jobs_path(@company, @job)
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :level_of_interest, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <%= render partial: "shared/errors", locals: { target: @category } %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit <%= @category.title %></h1>

<%= render partial: "form" %>

app/views/categories/index.html.erb
<h1>All Categories</h1>

<% @categories.each do |category| %>
  <ul>
    <li><%= link_to "#{category.title}", category_path(category) %></li>
  </ul>
<% end %>

app/views/categories/new.html.erb
<h1>Create Category</h1>

<%= render partial: "form" %>

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>

<ul>
  <% @category.jobs.each do |job| %>
    <li><%= link_to "#{job.title} at #{job.company.name}", company_job_path(job.company, job) %> </li>
  <% end %>
</ul>
<br>
<%= link_to "Edit", edit_category_path(@category) %>
<%= link_to "Delete", category_path(@category) %>

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
  <%= render partial: "shared/errors", locals: { target: @company } %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.submit %>
<% end %>

app/views/companies/city.html.erb
<h1><%= params[:location] %></h1>
<% @company.joins(:jobs).uniq.each do |company| %>
  <h3><%= company.name %></h3>
  <ul>
    <% company.jobs.each do |job| %>
      <li><%= link_to job.title, company_job_path(company, job) %></li>
    <% end %>
  </ul>
<% end %>

app/views/companies/edit.html.erb
<h2>Edit <%= @company.name %> here!</h2>

<%= render partial: "form" %>

app/views/companies/index.html.erb
<h3>All Companies</h3>

<% @companies.each do |company| %>
  <ul class=company_<%= company.id %>>
    <%= link_to company.name, company_path(company) %> - <%= company.city %><br>
    <%= link_to "Edit", edit_company_path(company) %>
    <%= link_to "Delete", company_path(company), method: "delete", data: {confirm: "Are you sure? All associated jobs will be deleted also!"} %>
  </ul>
<% end %>

<%= link_to "Add Company", new_company_path %>

app/views/companies/job_city_sort.html.erb
<h1>Location!!!</h1>

<ol>
  <% @ordered.each do |company|%>
    <li><%= link_to company.name, company_path(company) %><%= " in #{company.city}" %></li>
    <% company.jobs.each do |job| %>
      <ul>
        <li><%= link_to job.title, company_job_path(company, job) %></li>
      </ul>
    <% end %>
  <% end %>
</ol>

app/views/companies/new.html.erb
<h2>Create a new company here!</h2>

<%= render partial: "form" %>

app/views/companies/show.html.erb
All Jobs for <strong><%= @company.name %></strong>

<% @company.jobs.each do |job| %>
  <ul><%= job.title %></ul>
<% end %>

app/views/dashboard/index.html.erb
<h1>Dashboard!!!</h1>

<div class="level_of_interest">
  <h2>Job Count by Level of Interest</h2>
  <table>
    <tr>
      <th>Level of Interest</th>
      <th># of Jobs</th>
    </tr>
    <% @jobs.ordered_level_of_interest.each do |interest, count| %>
      <tr>
        <td><%= interest %></td>
        <td><%= count %></td>
      </tr>
    <% end %>
  </table>
</div>

<div class="top_three">
  <h2>Top Three Companies by Average Interest</h2>
  <ol>
    <% @top_three.each do |avg, company| %>
      <li><%= "#{company[0].name} has an average job interest of #{avg}"%></li>
    <% end %>
  </ol>
</div>

<div class="count_location">
<h2>Job Count by Location</h2>
  <% @cities.each do |city| %>
    <p><%= link_to city, "/companies?location=#{city}"%> has <%= Company.where(city: city).joins(:jobs).count %> jobs</p>
  <% end %>
</div>
<br>
<br>
<%= link_to "City Sort", "/companies?sort=location" %>
<%= link_to "Jobs by Interest", "/jobs?sort=interest" %>

app/views/jobs/_comment.html.erb
<h4>Comment from <%= time_ago_in_words(comment.updated_at) %></h4>
<p><%= comment.content %></p>

app/views/jobs/_contact.html.erb
  <tr>
    <td><%= contact.first_name %></td>
    <td><%= contact.last_name %></td>
    <td><%= contact.position %></td>
    <td><%= contact.email %></td>
  </tr>

app/views/jobs/_form.html.erb
<%= form_for [@company, @job] do |f| %>
  <%= render partial: "shared/errors", locals: { target: @company } %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :level_of_interest %>
  <%= f.number_field :level_of_interest %>

  <%= f.collection_select(:category_id, @categories, :id, :title) %>

  <%= f.submit %>
<% end %>

app/views/jobs/edit.html.erb
<h2>Edit <%= @job.title %> here</h2>

<%= render partial: "form"  %>

app/views/jobs/index.html.erb
All Jobs for <strong><%= @company.name %></strong>

<% @company.jobs.each do |job| %>
  <ul><%= link_to job.title, company_job_path(@company, job) %> at <%= job.company.name %></ul>
<% end %>

<%= link_to "Create Job", new_company_job_path %>
<br>
<br>
<% unless @company.contacts.empty? %>
  <h3>Contacts</h3>
  <table>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Position</th>
      <th>Email</th>
    </tr>
    <tr><%= render partial: "contact", collection: @company.contacts %></tr>
  </table>
  <br>
<% end %>

<%= form_for @contact do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :position %>
  <%= f.text_field :position %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= hidden_field_tag :company_id, @company.id %>

  <%= f.submit %>
<% end %>

app/views/jobs/interest.html.erb
<h1>JOBS BY INTEREST!!!</h1>
<ol>
  <% @jobs.interest.each do |job| %>
    <li><%= link_to job.title, company_job_path(job, job.company) %> at <%= job.company.name %>: <%= job.level_of_interest %></li>
  <% end %>
</ol>

app/views/jobs/new.html.erb
<h2>Create a new job at <%= @company.name %> here!</h2>

<%= render partial: "form" %>

<%= link_to "Create Category", new_category_path %>

app/views/jobs/show.html.erb
<h1>Job at <%= @job.company.name %></h1>

Title: <%= @job.title %>
<br>

Description: <%= @job.description %>
<br>

Level of Interest: <%= @job.level_of_interest %>
<br>

Company: <%= link_to @job.company.name, company_path(@job.company) %>
<br>

Category: <%= link_to @job.category.title, category_path(@job.category) %>
<br>

<%= link_to "Edit", edit_company_job_path(@job.company, @job) %>
<%= link_to "Delete", company_job_path(@job.company, @job), method: :delete, data: {confirm: "Are you sure you want to delete #{@job.title}"} %>

<h3>Comments</h3>

<%= render partial: "comment", collection: @comments %>
<%= form_for @comment do |f| %>
  <%= f.label :content, "Comment" %>
  <%= f.text_field :content %>
  <%= hidden_field_tag :job_id, @job.id %>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if target.errors.any? %>
  <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
  <ul>
    <% target.errors.full_messages.each do |message|  %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>